name: Hello
env:
  USER: "Mohan"
on: 
  push:
    branches: [main]
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello Dosto"

      - name: say hello to user
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Version of Docker, Python etc
        run: docker --version && python --version
      
